Models/TCustomer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace MyErp.Models
{
    public partial class TCustomer
    {
        public int CustId { get; set; }

        [Display(Name = "RaSoc")]
        [Required,StringLength(125)]
        public string CustRasoc { get; set; }

        [Display(Name = "NIF")]
        [Required,StringLength(10)]
        public string CustNif { get; set; }

        [Display(Name = "CrDate")]
        [Required,DataType(DataType.Date)]         
        public DateTime? CustCrDate { get; set; }

        [Display(Name = "Code")]
        [Required,StringLength(225)]
        public string CustCode { get; set; }

        [Display(Name = "Account")]
        [StringLength(225)]
        public string CustAcct { get; set; }

        [Display(Name = "Address")]
        [Required,StringLength(225)]
        public string CustAdStrt { get; set; }
        
        [Display(Name = "Address")]
        [StringLength(225)]
        public string CustAdAdit { get; set; }

        [Display(Name = "City")]
        [Required,StringLength(225)]
        public string CustAdCity { get; set; }

        [Display(Name = "Country")]
        [Required,StringLength(4)]
        public string CustAdCtry { get; set; }

        [Display(Name = "Phone")]
        [Required,StringLength(55)]
        public string CustCtPhone { get; set; }

        [Display(Name = "emailLOG")]
        [Required,StringLength(125)]
        public string CustCtEmailLog { get; set; }

        [Display(Name = "emailFIN")]
        [StringLength(125)]
        public string CustCtEmailFin { get; set; }

        [Display(Name = "Website")]
        [StringLength(225)]
        public string CustCtWeb { get; set; }

        [Display(Name = "ContactLOG")]
        [Required,StringLength(100)]
        public string CustCtEdilog { get; set; }

        [Display(Name = "ContactFIN")]
        [StringLength(100)]
        public string CustCtEdifin { get; set; }

        [Display(Name = "CBankAccount")]
        [StringLength(225)]
        public string CustCtBankAcc { get; set; }

        [Display(Name = "Status")]
        [StringLength(25)]
        public string CustStatus { get; set; }

        [Display(Name = "StatusDate")]
        [DataType(DataType.Date)]         
        public DateTime? CustStDate { get; set; }
    }
}

Controllers/TCustomerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyErp.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace MyErp.Controllers {
   [Authorize(Roles="Customer,Administrator")]
    public class TCustomerController : Controller {
        private readonly MyErpDBContext _dbContext;
        public TCustomerController(MyErpDBContext dbContext) {
            _dbContext = dbContext;
        }
        private void _loadCustomerViewBag( int? Pid,int? plant ,int? cust=0)
        {
                        var queryc = from p in _dbContext.TCustomers 
                        where p.CustId==Pid
                        select p;
            var qList=queryc.ToList();
            ViewBag.Customer=qList[0];


            var resulp = from p in _dbContext.TCCplants 
                        orderby p.CplantDeno
                        where p.CplantCustId==Pid
                        select new {p.CplantId ,p.CplantDeno};
            if (plant==0){
                try{
                    plant =resulp.ToList()[0].CplantId;
                }
                catch{plant =0;}
            }
            //ViewBag.ddlPlantVB = new SelectList(resulp.ToList(), "CplantId", "CplantDeno",plant); 
            //
            var _queryplan = (from p in _dbContext.TCCplants 
                        orderby p.CplantDeno
                        where p.CplantCustId==Pid
                        select new TCCplant {CplantId=p.CplantId ,CplantDeno=p.CplantDeno}).ToList();
            var _querypla0 = ( from p in _dbContext.TCCplants  
            select new TCCplant{CplantId=0,CplantDeno="Select a Plant"}).Distinct().ToList();
            var _queryplans = _querypla0.Concat(_queryplan);
            ViewBag.ddlPlantVB = new SelectList(_queryplans.ToList(), "CplantId", "CplantDeno",plant); 




            ViewData["Plant"]=plant;

            var queryplan = (from p in _dbContext.TCCplants 
                        orderby p.CplantDeno
                        select new TCCplant {CplantId=p.CplantId ,CplantDeno=p.CplantDeno}).ToList();
            var querypla0 = ( from p in _dbContext.TCCplants  
            select new TCCplant{CplantId=0,CplantDeno="Select a Plant"}).Distinct().ToList();
            var queryplans = querypla0.Concat(queryplan);
            ViewBag.ddlPlantX = new SelectList(queryplans.ToList(), "CplantId", "CplantDeno",0); 

            var querycust = (from p in _dbContext.TCustomers 
                        orderby p.CustRasoc
                        select new TCustomer {CustId=p.CustId ,CustRasoc=p.CustRasoc}).ToList();
            var querycus0 = ( from p in _dbContext.TCCplants  
            select new TCustomer{CustId=0,CustRasoc="Select a Customer"}).Distinct().ToList();
            var querycusts = querycus0.Concat(querycust);
            ViewBag.ddlCustoX = new SelectList(querycusts.ToList(), "CustId", "CustRasoc",0); 

            var querytruc = (from p in _dbContext.TCTrucks 
                        where p.TruckCustId==cust && p.TruckPlantId==plant
                        orderby p.TruckDeno
                        select new TCTruck {TruckId=p.TruckId ,TruckDeno=p.TruckDeno}).ToList();
            var querytru0 = ( from p in _dbContext.TCCplants  
            select new TCTruck{TruckId=0,TruckDeno="Select a Truck"}).Distinct().ToList();
            var querytrucs = querytru0.Concat(querytruc);
            ViewBag.ddlCustoX = new SelectList(querycusts.ToList(), "TruckId", "TruckDeno",0); 


        }
        private void CreateViewBags(int? id, int? prod, int? plant,int? cust =0,bool allpprods=false,DateTime? fHorizont = null)
        {

            var resulp = from p in _dbContext.TCCplants 
                        orderby p.CplantDeno
                        where p.CplantCustId==id
                        select new {p.CplantId ,p.CplantDeno};
            if (plant==0){
                try{
                    plant =resulp.ToList()[0].CplantId;
                }
                catch{plant =0;}
            }
            //ViewBag.ddlPlantVB = new SelectList(resulp.ToList(), "CplantId", "CplantDeno",plant); 


            var _queryplan = (from p in _dbContext.TCCplants 
                        orderby p.CplantDeno
                        where p.CplantCustId==id
                        select new TCCplant {CplantId=p.CplantId ,CplantDeno=p.CplantDeno}).ToList();
            var _querypla0 = ( from p in _dbContext.TCCplants  
            select new TCCplant{CplantId=0,CplantDeno="Select a Plant"}).Distinct().ToList();
            var _queryplans = _querypla0.Concat(_queryplan);
            ViewBag.ddlPlantVB = new SelectList(_queryplans.ToList(), "CplantId", "CplantDeno",plant); 



            ViewData["Plant"]=plant;
            ViewData["Prod"]=prod;

            var queryplan = (from p in _dbContext.TCCplants 
                        orderby p.CplantDeno
                        select new TCCplant {CplantId=p.CplantId ,CplantDeno=p.CplantDeno}).ToList();
            var querypla0 = ( from p in _dbContext.TCCplants  
            select new TCCplant{CplantId=0,CplantDeno="Select a Plant"}).Distinct().ToList();
            var queryplans = querypla0.Concat(queryplan);
            ViewBag.ddlPlantX = new SelectList(queryplans.ToList(), "CplantId", "CplantDeno",0); 

            var querycust = (from p in _dbContext.TCustomers 
                        orderby p.CustRasoc
                        select new TCustomer {CustId=p.CustId ,CustRasoc=p.CustRasoc}).ToList();
            var querycus0 = ( from p in _dbContext.TCCplants  
            select new TCustomer{CustId=0,CustRasoc="Select a Customer"}).Distinct().ToList();
            var querycusts = querycus0.Concat(querycust);
            ViewBag.ddlCustoX = new SelectList(querycusts.ToList(), "CustId", "CustRasoc",0); 

            var querytruc = (from p in _dbContext.TCTrucks 
                        where p.TruckCustId==cust //&& p.TruckPlantId==plant
                        orderby p.TruckDeno
                        select new TCTruck {TruckId=p.TruckId ,TruckDeno=p.TruckDeno}).ToList();
            var querytru0 = ( from p in _dbContext.TCTrucks  
            select new TCTruck{TruckId=0,TruckDeno="Select a Truck"}).Distinct().ToList();
            var querytrucs = querytru0.Concat(querytruc);
            ViewBag.ddlTruckX = new SelectList(querytrucs.ToList(), "TruckId", "TruckDeno",0); 


//se ha cambiado el diseño de modo que el producto no esta asignado a la planta
//solamante a nivel del pedido se asigna a la planta una referncia de producto de un cliente
//que puede estar asignado a varias plantas del mismo cliente
            var resulpo = from or in _dbContext.TCPorders
                            where or.CpocustId==id && or.CpocplantId==plant &&or.CpocprodId !=null
                            join mat in _dbContext.TMaterials
                            on or.CpocprodId equals mat.MatId
                            into Popro
                          from Pop in Popro.DefaultIfEmpty()
                        where (Pop.MatId!=0)
                        orderby Pop.MatDescr                        
                        select new {Pop.MatId ,Pop.MatDescr};

            var resuld = from p in _dbContext.TCCproducts 
                        join mat in _dbContext.TMaterials
                        on p.CprodMatInt equals mat.MatId
                        orderby mat.MatDescr
                        where p.CprodCustId==id //&& p.CprodCplantId==plant
                        //&& !_dbContext.TCPorders.Any(x => x.CpocprodId == p.CprodMatInt && x.CpocplantId == plant)
                        //p.CprodId not in ( from or in _dbContext.TCPorders select CpocprodId)
                        select new {mat.MatId ,mat.MatDescr};
                        
                var result = from p in _dbContext.TCCproducts 
                            join mat in _dbContext.TMaterials
                            on p.CprodMatInt equals mat.MatId
                            orderby mat.MatRefer
                            where p.CprodCustId==id //&&p.CprodCplantId==plant
                            select new {mat.MatId ,mat.MatRefer};
                        
            var resulpo_pr = from or in _dbContext.TCPorders
                            where or.CpocustId==id && or.CpocplantId==plant
                            join mat in _dbContext.TMaterials
                            on or.CpocprodId equals mat.MatId 
                            into Popro
                          from Pop in Popro.DefaultIfEmpty() 
                        where Pop.MatId==prod   
                        select new {Pop.MatId };        
            var resulpo_pl = from or in _dbContext.TCPorders
                            where or.CpocustId==id && or.CpocplantId==plant
                            join mat in _dbContext.TMaterials
                            on or.CpocprodId equals mat.MatId 
                            into Popro
                          from Pop in Popro.DefaultIfEmpty() 
                        select new {Pop.MatId };                  
            var result_pr = from p in _dbContext.TCCproducts 
                            join mat in _dbContext.TMaterials
                            on p.CprodMatInt equals mat.MatId
                        orderby mat.MatRefer
                        where p.CprodCustId==id && mat.MatId==prod //&&p.CprodCplantId==plant 
                        select new {mat.MatId ,mat.MatRefer};
            try{
                prod =resulpo_pr.ToList()[0].MatId; //ddlrefer puede contnener una referencia que no corresponde con la planta de ddl plabnta que ha cambiado
            }
            catch{prod=0;}   
                                       //ponemos prod a cer y lo tratamoa a continuacion
            if (prod==0 || prod==null){                 //si prod es cero le signa una referencia de la planta en cuestion

Views/TCustomer/PoCreate.cshtml
@using MyErp.Models
@model TCPorder
@using MyErp.Resources
@inject LocService SharedLocalizer
@{
    Layout = "_LayCus";
}
@functions {
    int? Planta(){
        int? retcol = (int?)ViewData["Plant"];
        return retcol;
    }
}
@{
    try{
        Model.CpocplantId=Convert.ToInt32(ViewData["Plant"].ToString());
    }
    catch{}
}
<div class="style-data">
<h3>@SharedLocalizer.GetLocalizedHtmlString("AddPORecord")</h3>
</div>
@using (Html.BeginForm()) {
    <div class="div-edit">
    @Html.ValidationSummary(true)
    <div class ="invisible">
        <tr>
            <input type="hidden" name="CpocustId" value="@(((TCustomer)ViewBag.Customer).CustId)"/>
            @*<input type="hidden" name="CpocplantId" value="@Planta()"/>*@
            <td>@SharedLocalizer.GetLocalizedHtmlString("Customer"):</td>
            <td>@(((TCustomer)ViewBag.Customer).CustRasoc)</td>
        </tr>
    </div>
    @*
    <div class ="visible">
        <tr>
            <td>Custome:</td>
            <td>@(((TCustomer)ViewBag.Customer).CustRasoc)</td>
            <td> </td>
            <td>@(((TCustomer)ViewBag.Customer).CustNif)</td>
        </tr>
    </div>
    *@
    <div class ="div-edit">
        <tr>
            @using (Html.BeginForm("Edit","TCustomer",FormMethod.Post)) {        
            <div class ="div-edit">
            <td>@Html.LabelFor(p => p.CpocplantId,new { @class = "norm-lab-text",})</td>
            <td class="norm-text">
                @Html.DropDownListFor(p => p.CpocplantId,(SelectList)ViewBag.ddlPlantVB,"",new { @class = "norm-tb-text" })
           
            </td>
            </div>
            }
        </tr>
    </div>

    <table class="table-edit">
        <hr style="width:100%;text-align:left;margin-left:0">
        <tr>
            <td><input type="submit" class="dropbtn" value="Add"  name="actionType"/></td>
            <td><input type="submit" class="dropbtn" value="Cancel" name="actionType"/></td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.Cpopo,new { @class = "norm-lab-text",})</td>
            <td>@Html.EditorFor(p => p.Cpopo, new { htmlAttributes = new { @class = "norm-tb-text", @style = "width:150px" } })</td>
            <td>@Html.ValidationMessageFor(p => p.Cpopo)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.Cpodate,new { @class = "norm-lab-text",})</td>
            <td>@Html.EditorFor(p => p.Cpodate, new { htmlAttributes = new { @class = "norm-tb-text"} })</td>
            <td>@Html.ValidationMessageFor(p => p.Cpodate)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.CporeferEx,new { @class = "norm-lab-text",})</td>
            <td>@Html.EditorFor(p => p.CporeferEx, new { htmlAttributes = new { @class = "norm-tb-text", @style = "width:170px" } })</td>
            <td>@Html.ValidationMessageFor(p => p.CporeferEx)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.CpodescEx,new { @class = "norm-lab-text" })</td>
            <td>@Html.EditorFor(p => p.CpodescEx, new { htmlAttributes = new { @class = "norm-tb-text" , @style = "width:450px" } })</td>
            <td>@Html.ValidationMessageFor(p => p.CpodescEx)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.CpocprodId,new { @class = "norm-lab-text",})</td>
            <td class="norm-text">
                @Html.DropDownListFor(p => p.CpocprodId,(SelectList)ViewBag.ddlReferVD,"",new { @class = "norm-tb-text" })
                <td>@Html.ValidationMessageFor(p => p.CpocprodId)</td>
            </td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.Cpoprice,new { @class = "norm-lab-text" })</td>
            <td>@Html.EditorFor(p => p.Cpoprice, new { htmlAttributes = new { @class = "norm-tb-text", @style = "width:90px" } })</td>
            <td>@Html.ValidationMessageFor(p => p.Cpoprice)</td>
        </tr>        
        <tr>        
            <td>@Html.LabelFor(p => p.Cpocurcy,new { @class = "norm-lab-text" })</td>
            <td>
                @Html.DropDownListFor(p => p.Cpocurcy,
               new SelectList(DataSource.GetCurrency(), "Code", "Name"),new { @class = "norm-tb-text" })
            </td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.Cpostatus,new { @class = "norm-lab-text",})</td>
            <td>@Html.EditorFor(p => p.Cpostatus, new { htmlAttributes = new { @class = "norm-tb-text", @style = "width:170px" } })</td>
            <td>@Html.ValidationMessageFor(p => p.Cpostatus)</td>
            <input type="hidden" name="CpocustId" value="@(((TCustomer)ViewBag.Customer).CustId)"/>
            <input type="hidden" name="CpocplantId" value="@Planta()"/>
        </tr>
    </table>
    </div>
}

Views/TCustomer/PoEdit.cshtml
@using MyErp.Models
@model TCPorder
@using MyErp.Resources
@inject LocService SharedLocalizer
@{
    Layout = "_LayCus";
}
<div class="style-data">
<h3>@SharedLocalizer.GetLocalizedHtmlString("EditPORecord")</h3>
</div>
@using (Html.BeginForm()) {
    <div class="visible">
    @Html.HiddenFor(p => p.Cpoid)
    @Html.HiddenFor(p => p.CpocustId)
    @Html.ValidationSummary(true)
    @*
    <div class ="visible">
        <tr>
            <td>Custome:</td>
            <td>@(((TCustomer)ViewBag.Customer).CustRasoc)</td>
            <td> </td>
            <td>@(((TCustomer)ViewBag.Customer).CustNif)</td>
        </tr>
    </div>
    *@
    <div class ="div-edit">
        <tr>
            @using (Html.BeginForm("Edit","TCustomer",FormMethod.Post)) {        
            <div class ="visible">
            <td>@Html.LabelFor(p => p.CpocplantId,new { @class = "norm-lab-text",})</td>
            <td class="norm-text">
                @Html.DropDownListFor(p => p.CpocplantId,(SelectList)ViewBag.ddlPlantVB,"",new { @class = "norm-tb-text" })
           
            </td>
            </div>
            }
        </tr>
    </div>

    <table class="table-edit">
        <hr style="width:100%;text-align:left;margin-left:0">
        <tr>
            <td><input type="submit" class="dropbtn" value="Update"  name="actionType"/></td>
            <td><input type="submit" class="dropbtn" value="Cancel" name="actionType"/></td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.Cpopo,new { @class = "norm-lab-text",})</td>
            <td>@Html.EditorFor(p => p.Cpopo, new { htmlAttributes = new { @class = "norm-tb-text", @style = "width:150px" } })</td>
            <td>@Html.ValidationMessageFor(p => p.Cpopo)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.Cpodate,new { @class = "norm-lab-text",})</td>
            <td>@Html.EditorFor(p => p.Cpodate, new { htmlAttributes = new { @class = "norm-tb-text"} })</td>
            <td>@Html.ValidationMessageFor(p => p.Cpodate)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.CporeferEx,new { @class = "norm-lab-text",})</td>
            <td>@Html.EditorFor(p => p.CporeferEx, new { htmlAttributes = new { @class = "norm-tb-text", @style = "width:170px" } })</td>
            <td>@Html.ValidationMessageFor(p => p.CporeferEx)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.CpodescEx,new { @class = "norm-lab-text" })</td>
            <td>@Html.EditorFor(p => p.CpodescEx, new { htmlAttributes = new { @class = "norm-tb-text" , @style = "width:450px" } })</td>
            <td>@Html.ValidationMessageFor(p => p.CpodescEx)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.CpocprodId,new { @class = "norm-lab-text",})</td>
            <td class="norm-text">
                @Html.DropDownListFor(p => p.CpocprodId,(SelectList)ViewBag.ddlReferVD,"",new { @class = "norm-tb-text" })
                <td>@Html.ValidationMessageFor(p => p.CpocprodId)</td>
            </td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.Cpoprice,new { @class = "norm-lab-text" })</td>
            <td>@Html.EditorFor(p => p.Cpoprice, new { htmlAttributes = new { @class = "norm-tb-text", @style = "width:90px" } })</td>
            <td>@Html.ValidationMessageFor(p => p.Cpoprice)</td>
        </tr>        
        <tr>        
            <td>@Html.LabelFor(p => p.Cpocurcy,new { @class = "norm-lab-text" })</td>
            <td>
                @Html.DropDownListFor(p => p.Cpocurcy,
               new SelectList(DataSource.GetCurrency(), "Code", "Name"),new { @class = "norm-tb-text" })
            </td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.Cpostatus,new { @class = "norm-lab-text",})</td>
            <td>@Html.EditorFor(p => p.Cpostatus, new { htmlAttributes = new { @class = "norm-tb-text", @style = "width:170px" } })</td>
            <td>@Html.ValidationMessageFor(p => p.Cpostatus)</td>
        </tr>
    </table>
    </div>
}

Views/TCustomer/ProCreate.cshtml
@using MyErp.Models
@model TCCproduct
@using MyErp.Resources
@inject LocService SharedLocalizer
@{
    Layout = "_LayCus";
}
@functions {
    int? Planta(){
        int? retcol = (int?)ViewData["Plant"];
        return retcol;
    }
}
<div class="style-data">
<h3>@SharedLocalizer.GetLocalizedHtmlString("AddProdRecord")</h3>
</div>
@using (Html.BeginForm()) {
   <div class="div-edit">
    @Html.ValidationSummary(true)
    <table class="table-edit">
        <hr style="width:100%;text-align:left;margin-left:0">
        <tr>
            <td><input type="submit" class="dropbtn" value="Add"  name="actionType"/></td>
            <td><input type="submit" class="dropbtn" value="Cancel" name="actionType"/></td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.CprodMatInt,new { @class = "norm-lab-text",})</td>
            <td class="norm-text">
                @Html.DropDownListFor(p => p.CprodMatInt,(SelectList)ViewBag.ddlMatCOM,"",new { @class = "norm-tb-text" })
                <td>@Html.ValidationMessageFor(p => p.CprodMatInt)</td>
            </td>

        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.CprodCrDate,new { @class = "norm-lab-text" })</td>
            <td>@Html.EditorFor(p => p.CprodCrDate, new { htmlAttributes = new { @class = "norm-tb-text" } })</td>
            <td>@Html.ValidationMessageFor(p => p.CprodCrDate)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.CprodStatus,new { @class = "norm-lab-text" })</td>
            <td>@Html.EditorFor(p => p.CprodStatus, new { htmlAttributes = new { @class = "norm-tb-text", @style = "width:90px" } })</td>
            <td>@Html.ValidationMessageFor(p => p.CprodStatus)</td>
            <input type="hidden" name="CProdCustId" value="@(((TCustomer)ViewBag.Customer).CustId)"/>
            <input type="hidden" name="CProdCPlantId" value="@Planta()"/>
        </tr>        
    </table>
    </div>
}

Views/TCustomer/ProEdit.cshtml
@using MyErp.Models
@model TCCproduct
@using MyErp.Resources
@inject LocService SharedLocalizer
@{
    Layout = "_LayCus";
}
<div class="style-data">
<h3>@SharedLocalizer.GetLocalizedHtmlString("EditProdRecord")</h3>
</div>
@using (Html.BeginForm()) {
    <div class="div-edit">
    @Html.HiddenFor(p => p.CprodId)
    @Html.HiddenFor(p => p.CprodCustId)
    @Html.ValidationSummary(true)
    @*
    <div class ="visible">
        <tr>
            <td>Custome:</td>
            <td>@(((TCustomer)ViewBag.Customer).CustRasoc)</td>
            <td> </td>
            <td>@(((TCustomer)ViewBag.Customer).CustNif)</td>
        </tr>
    </div>
    *@
@*
    <div class ="div-bold">
        <tr>
            @using (Html.BeginForm("Edit","TCustomer",FormMethod.Post)) {        
            <div class ="visible">
            <td>@Html.LabelFor(p => p.CprodCplantId,new { @class = "norm-text",})</td>
            <td class="norm-text">
                <!--@ViewData["Plant"]-->
                @Html.DropDownListFor(p => p.CprodCplantId,(SelectList)ViewBag.ddlPlantVB,"",new { @class = "norm-text" })
           
            </td>
            </div>
            }
        </tr>
    </div>
*@
    <table class="table-edit">
        <hr style="width:100%;text-align:left;margin-left:0">
        <tr>
            <td><input type="submit" class="dropbtn" value="Update"  name="actionType"/></td>
            <td><input type="submit" class="dropbtn" value="Cancel" name="actionType"/></td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.CprodMatInt,new { @class = "norm-lab-text",})</td>
            <td class="norm-text">
                <!--@ViewData["Plant"]-->
                @Html.DropDownListFor(p => p.CprodMatInt,(SelectList)ViewBag.ddlMatCOM,"",new { @class = "norm-tb-text" })
                <td>@Html.ValidationMessageFor(p => p.CprodMatInt)</td>
            </td>

        </tr>
@*
        <tr>
            <td>@Html.LabelFor(p => p.CprodRefInt,new { @class = "norm-text",})</td>
            <td>@Html.EditorFor(p => p.CprodRefInt, new { htmlAttributes = new { @class = "norm-text", @style = "width:150px" } })</td>
            <td>@Html.ValidationMessageFor(p => p.CprodRefInt)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.CprodDescInt,new { @class = "norm-text",})</td>
            <td>@Html.EditorFor(p => p.CprodDescInt, new { htmlAttributes = new { @class = "norm-text", @style = "width:450px" } })</td>
            <td>@Html.ValidationMessageFor(p => p.CprodDescInt)</td>
        </tr>
*@
        <tr>
            <td>@Html.LabelFor(p => p.CprodCrDate,new { @class = "norm-lab-text" })</td>
            <td>@Html.EditorFor(p => p.CprodCrDate, new { htmlAttributes = new { @class = "norm-tb-text" } })</td>
            <td>@Html.ValidationMessageFor(p => p.CprodCrDate)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.CprodStatus,new { @class = "norm-lab-text" })</td>
            <td>@Html.EditorFor(p => p.CprodStatus, new { htmlAttributes = new { @class = "norm-tb-text", @style = "width:90px" } })</td>
            <td>@Html.ValidationMessageFor(p => p.CprodStatus)</td>
        </tr>        
    </table>
    </div>
}