Models/TPerson.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace MyErp.Models
{
    public partial class TPerson
    {
        public int PerId { get; set; }

        [Display(Name="DNI")]
        [Required(ErrorMessage="mDNI"),StringLength(10)]
        public string PerDni { get; set; }

        [Display(Name="BirdDate")]
        [Required(ErrorMessage="mBirD"),DataType(DataType.Date)]         
        public DateTime? PerBird { get; set; }

        [Display(Name="CityOrigin")]
        [Required(ErrorMessage="mCitB"),StringLength(100)]
        public string PerBiCity { get; set; }

        [Display(Name="CountryOrigin")]
        [Required(ErrorMessage="mCtrOr"),StringLength(4)]
        public string PerBiCtry { get; set; }

        [Display(Name="Name")]
        [Required(ErrorMessage="mName"),StringLength(100)]
        public string PerName { get; set; }

        [Display(Name="Surname")]
        [Required(ErrorMessage="mSname"),StringLength(100)]
        public string PerName1 { get; set; }

        [Display(Name="Adress")]
        [Required(ErrorMessage="mAdr"),StringLength(255)]
        public string PerAddr { get; set; }

        [Display(Name="AdressAd")]
        [Required(ErrorMessage="mAdr"),StringLength(255)]
        public string PerAddr1 { get; set; }

        [Display(Name="CountryRes")]
        [Required(ErrorMessage="mCtrOr"),StringLength(4)]
        public string PerAddCtry { get; set; }

        [Display(Name="ContractDate")]
        [Required(ErrorMessage="mConD"),DataType(DataType.Date)]         
        public DateTime? PerContDate { get; set; }

        [Display(Name="EntryDate")]
        [Required(ErrorMessage="mEntD"),DataType(DataType.Date)]         
        public DateTime? PerEntDate { get; set; }

        [Display(Name="ExitDate")]
        [DataType(DataType.Date)]         
        public DateTime? PerExiDate { get; set; }
    }
}

Controllers/TPersonController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using MyErp.Models;
using System;
using System.Linq;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyErp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.SqlServer;
using Microsoft.Data.SqlClient;
using Microsoft.AspNetCore.Authorization;
using Microsoft.IdentityModel.Protocols;
using Microsoft.Extensions.Configuration;
using System.Data;

namespace MyErp.Controllers {
    [Authorize(Roles="Administrator,HR")]
    public class TPersonController : Controller {
        private readonly MyErpDBContext _dbContext;
        /*
        public TPersonController(MyErpDBContext dbContext) {
            _dbContext = dbContext;
        }
        */
        private readonly ILogger<TPersonController> _logger;    
        /* esta version de localizacion no la utilizamos ahora
        private readonly IStringLocalizer<TPersonController> _localizer;

        public TPersonController(MyErpDBContext dbContext,IStringLocalizer<TPersonController> localizer,
        
        ILogger<TPersonController> logger)
        {
            _dbContext = dbContext;
            _localizer = (IStringLocalizer<TPersonController>)localizer;
            _logger = (ILogger<TPersonController>)logger;
        }    
        */

        public TPersonController(MyErpDBContext dbContext,ILogger<TPersonController> logger)
        {
            _dbContext = dbContext;
            _logger = (ILogger<TPersonController>)logger;
        }    

        private void CreateViewBags(int? id)

        {
            var querype = from p in _dbContext.TPersons 
                        orderby p.PerName,p.PerName1
                        select p;
            var qListpe = querype.ToList();
            ViewBag.ListPerson=qListpe;

            var queryca = from p in _dbContext.TPCareers 
                        orderby p.CareDate
                        where p.CarePerId==id
                        select p;
            var qListca = queryca.ToList();
            ViewBag.ListCareer=qListca;

            var queryco = from p in _dbContext.TPContracts 
                        orderby p.ConRevDate
                        where p.ConPerId==id
                        select p;
            var qListco = queryco.ToList();
            ViewBag.ListContract=qListco;

            var querycu = from p in _dbContext.TPCurrics 
                        orderby p.CurrRevDate
                        where p.CurrPerId==id
                        select p;
            var qListcu = querycu.ToList();
            ViewBag.ListCurric=qListcu;

            var querypa = from p in _dbContext.TPPays 
                        orderby p.PayStDate
                        where p.PayPerId==id
                        select p;
            var qListpa = querypa.ToList();
            ViewBag.ListPay=qListpa;

            var querypre = from p in _dbContext.TPPresens 
                        orderby p.PresDateEvent
                        where p.PresPerId==id
                        select p;
            var qListpre = querypre.ToList();
            ViewBag.ListPre=qListpre;

            var queryre = from p in _dbContext.TPReviews 
                        orderby p.RevDate
                        where p.RevPerId==id
                        select p;
            var qListre = queryre.ToList();
            ViewBag.ListRev=qListre;

            var querytra = from p in _dbContext.TPTrains 
                        orderby p.TrainDate
                        where p.TrainPerId==id
                        select p;
            var qListra = querytra.ToList();
            ViewBag.ListTra=qListra;
        }
        private void loadPersonViewBag( int? Pid)
        {
                        var queryc = from p in _dbContext.TPersons 
                        where p.PerId==Pid
                        select p;
            var qList=queryc.ToList();
            ViewBag.Person=qList[0];

        }
        /*
        private Microsoft.AspNetCore.Http.IRequestCookieCollection getCookies()
        {
            Microsoft.AspNetCore.Http.IRequestCookieCollection ret =Request.Cookies;
            return ret;
        }
        */
        public IActionResult Index(int filter,string pNam, string pNam1,string actionType) {
            //esto solo testimonial  -------------------------------
            string curpag="";
            try{
            curpag=Request.Cookies["_1-currentpage"].ToString().TrimStart().TrimEnd();
            }
            catch{}
            //lo anterior solo testimonial --------------------------
            if (actionType=="Cancel"){filter=0;}
            //string variable =_localizer["Indexmessage"];
            //ViewData["Title"] = _localizer["Indexmessage"];
            ViewData["Filter"]=filter;
            ViewData["Fil1"]=pNam;
            ViewData["Fil2"]=pNam1;
            var dbContext = new MyErpDBContext();
            try{
             var model = _dbContext.TPersons.OrderBy(p => p.PerId).ToList();
            /*
             var model = _dbContext.TPersons.OrderBy(p => p.PerName1).ThenBy(p=> p.PerName).ToList();
             if (filter ==2){
                var queryc = from p in _dbContext.TPersons 
                        where (p.PerName.Contains(pNam) || pNam ==null ) && (p.PerName1.Contains(pNam1) ||pNam1==null)
                        orderby p.PerName1, p.PerName
                        select p;
                var qList=queryc.ToList();
                model = qList;
             
             }
             */
             //ViewData["CookiesGrid"]=getCookies();
             return View(model);
            }
            catch(Exception ex)
            {
                string mensaje = ex.Message;
                return View("Error");}
            
        }
        public IActionResult ShowDetail(int id) {
            var model = _dbContext.TPersons
                .SingleOrDefault(u => u.PerId.Equals(id));
            if (model != null)
                return View("Detail", model);
            else
                return RedirectToAction("Index");
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Create() {
            return View();      
        }

        [HttpPost]
        public IActionResult Create(TPerson person, string actionType) {
            if(actionType=="Add"){
            if (ModelState.IsValid){
            try{
                _dbContext.TPersons.Add(person); 
                _dbContext.SaveChanges();
                }
            catch{}
            }
            else{                
                return View(person);
                }
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult CarCreate(int Pid) {
            var queryc = from p in _dbContext.TPersons 
                        where p.PerId==Pid
                        select p;
            var qList=queryc.ToList();
            ViewBag.Person=qList[0];

             var model = _dbContext.TPersons
                .SingleOrDefault(u => u.PerId.Equals(Pid));

            string dName = model.PerName1+" " +model.PerName;
            ViewData["dName"]=dName;
            ViewData["PerId"]=Pid;

            ViewData["panel"]=2;
            return View();      
        }

        [HttpPost]
        public IActionResult CarCreate(TPCareer career,int Pid, string actionType) {
            if(actionType=="Add"){
            if (ModelState.IsValid){
            try{
                _dbContext.TPCareers.Add(career); 
                _dbContext.SaveChanges();
            }
            catch{return View("Error");}
            }
            else{
                    loadPersonViewBag(Pid);
                    return View(career);
            }
            }
            var model = _dbContext.TPersons
                .SingleOrDefault(u => u.PerId.Equals(Pid));

            string dName = model.PerName1+" " +model.PerName;
            ViewData["dName"]=dName;
            ViewData["PerId"]=Pid;

            CreateViewBags(Pid);    
            ViewData["panel"]=2;
            //return View("Edit",model);
            return RedirectToAction("Edit", new { id = Pid,panel =2,move=0 });

        }

        [HttpGet]
        public IActionResult ConCreate(int Pid) {
            var queryc = from p in _dbContext.TPersons 
                        where p.PerId==Pid
                        select p;
            var qList=queryc.ToList();
            ViewBag.Person=qList[0];

             var model = _dbContext.TPersons
                .SingleOrDefault(u => u.PerId.Equals(Pid));

            string dName = model.PerName1+" " +model.PerName;
            ViewData["dName"]=dName;
            ViewData["PerId"]=Pid;

            return View();      
        }

        [HttpPost]
        public IActionResult ConCreate(TPContract contract,int Pid, string actionType) {
            if (actionType=="Add"){
            if (ModelState.IsValid){
            try{
                _dbContext.TPContracts.Add(contract); 
                _dbContext.SaveChanges();
            }
            catch{return View("Error");}
            }
            else{
                    loadPersonViewBag(Pid);
                    return View(contract);
            }
            }
            var model = _dbContext.TPersons
                .SingleOrDefault(u => u.PerId.Equals(Pid));

            string dName = model.PerName1+" " +model.PerName;
            ViewData["dName"]=dName;
            ViewData["PerId"]=Pid;

            CreateViewBags(Pid);
            ViewData["panel"]=3;
            return RedirectToAction("Edit", new { id = Pid,panel =3,move=0 });
        }

        [HttpGet]
        public IActionResult CurCreate(int Pid) {
            loadPersonViewBag(Pid);

Views/TPerson/CarCreate.cshtml
@using MyErp.Models
@model TPCareer
@using MyErp.Resources
@inject LocService SharedLocalizer
@{
    Layout = "_LayPer";
}
<div class="style-data">
<h3>@SharedLocalizer.GetLocalizedHtmlString("CareerCreate")</h3>
</div>
@using (Html.BeginForm()) {
    <div class="visible">
    @Html.ValidationSummary(true)
    @*
    <table class="table-norm" border ="1">
        <tr>
            <input type="hidden" name="CarePerId" value="@(((TPerson)ViewBag.Person).PerId)"/>
            <td>@SharedLocalizer.GetLocalizedHtmlString("Name")</td>
            <td>@(((TPerson)ViewBag.Person).PerName)</td>
        </tr>
        <tr>
            <td>@SharedLocalizer.GetLocalizedHtmlString("Surnames")</td>
            <td>@(((TPerson)ViewBag.Person).PerName1)</td>
        </tr>
    </table>
    *@
    <table class="table-edit" >
        <hr style="width:100%;text-align:left;margin-left:0">
        <tr>
            <td>
            <input type="submit" value="Add" class="dropbtn" name="actionType"/>
            <input type="submit" value="Cancel" class="dropbtn" name="actionType"/>
            </td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.CareDate,new { @class = "norm-lab-text",})</td>
            <td>@Html.EditorFor(p => p.CareDate, new { htmlAttributes = new { @class = "norm-tb-text"} })</td>
        </tr>
        <tr>
            <td></td>
            <td>@Html.ValidationMessageFor(p => p.CareDate)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.CarePosit,new { @class = "norm-lab-text",})</td>
            <td>@Html.EditorFor(p => p.CarePosit, new { htmlAttributes = new { @class = "norm-tb-text", @style = "width:125px"} })</td>
        </tr>
        <tr>
            <td></td>
            <td>@Html.ValidationMessageFor(p => p.CarePosit)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.CareObser,new { @class = "norm-lab-text",})</td>
            <td>@Html.EditorFor(p => p.CareObser, new { htmlAttributes = new { @class = "norm-tb-text", @style = "width:425px"} })</td>
        </tr>
        <tr>
            <td></td>
            <td>@Html.ValidationMessageFor(p => p.CareObser)</td>
            <input type="hidden" name="CarePerId" value="@(((TPerson)ViewBag.Person).PerId)"/>
       </tr>
    </table>
    </div>
}

Views/TPerson/CarEdit.cshtml
@using MyErp.Models
@model TPCareer
@using MyErp.Resources
@inject LocService SharedLocalizer
@{
    Layout = "_LayPer";
}
<div class="style-data">
<h3>@SharedLocalizer.GetLocalizedHtmlString("CareerEdit")</h3>
</div>
@using (Html.BeginForm()) {
    <div class="visible">
    @Html.HiddenFor(p => p.CareId)
    @Html.HiddenFor(p => p.CarePerId)
    @Html.ValidationSummary(true)
    @*
    <table class="table-norm" border ="1">
        <tr>
            <td>@SharedLocalizer.GetLocalizedHtmlString("Name")</td>
            <td>@(((TPerson)ViewBag.Person).PerName)</td>
        </tr>
        <tr>
            <td>@SharedLocalizer.GetLocalizedHtmlString("Surnames")</td>
            <td>@(((TPerson)ViewBag.Person).PerName1)</td>
        </tr>
    </table>
    *@
    <table class="table-edit" >
        <hr style="width:100%;text-align:left;margin-left:0">
       <tr>
            <td>
            <input type="submit" value="Update" class="dropbtn" name="actionType"/>
            <input type="submit" value="Cancel" class="dropbtn" name="actionType"/>
            </td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.CareDate,new { @class = "norm-lab-text",})</td>
            <td>@Html.EditorFor(p => p.CareDate, new { htmlAttributes = new { @class = "norm-tb-text"} })</td>
        </tr>
        <tr>
            <td></td>
            <td>@Html.ValidationMessageFor(p => p.CareDate)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.CarePosit,new { @class = "norm-lab-text",})</td>
            <td>@Html.EditorFor(p => p.CarePosit, new { htmlAttributes = new { @class = "norm-tb-text", @style = "width:125px"} })</td>
        </tr>
        <tr>
            <td></td>
            <td>@Html.ValidationMessageFor(p => p.CarePosit)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.CareObser,new { @class = "norm-lab-text",})</td>
            <td>@Html.EditorFor(p => p.CareObser, new { htmlAttributes = new { @class = "norm-tb-text", @style = "width:425px"} })</td>
        </tr>
        <tr>
            <td></td>
            <td>@Html.ValidationMessageFor(p => p.CareObser)</td>
        </tr>
    </table>
    </div>
}

Views/TPerson/CurEdit.cshtml
@using MyErp.Models
@model TPCurric
@using MyErp.Resources
@inject LocService SharedLocalizer
@{
    Layout = "_LayPer";
}

<div class="style-data">
<h3>@SharedLocalizer.GetLocalizedHtmlString("CurriculumEdit")</h3>
</div>
@using (Html.BeginForm()) {
    <div class="visible">
    @Html.ValidationSummary(true)
    @Html.HiddenFor(p => p.CurrId)
    @Html.HiddenFor(p => p.CurrPerId)
    @*
    <div class ="div-bold">
        <tr>
            <td>@SharedLocalizer.GetLocalizedHtmlString("Name") :</td>
            <td>@(((TPerson)ViewBag.Person).PerName)</td>
            <td> </td>
            <td>@(((TPerson)ViewBag.Person).PerName1)</td>
        </tr>    
    </div>
    *@
    <table class="table-edit" border ="0">
        <hr style="width:100%;text-align:left;margin-left:0">
        <tr>
            <td>
            <input type="submit" value="Update"  class="dropbtn" name="actionType"/>
            <input type="submit" value="Cancel" class="dropbtn" name="actionType"/>
            </td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.CurrRevDate, new { htmlAttributes = new { @class = "norm-lab-text"} })</td>
            <td>@Html.EditorFor(p => p.CurrRevDate, new { htmlAttributes = new { @class = "norm-tb-text"} })</td>
            <td>@Html.ValidationMessageFor(p => p.CurrRevDate)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.CurrArea, new { htmlAttributes = new { @class = "norm-lab-text", @style = "width:110px" } })</td>
            <td>@Html.EditorFor(p => p.CurrArea, new { htmlAttributes = new { @class = "norm-tb-text", @style = "width:110px" } })</td>
            <td>@Html.ValidationMessageFor(p => p.CurrArea)</td>
        </tr>        
        <tr>
            <td>@Html.LabelFor(p => p.CurrAreaDesc, new { htmlAttributes = new { @class = "norm-lab-text", @style = "width:300px" } })</td>
            <td>@Html.EditorFor(p => p.CurrAreaDesc, new { htmlAttributes = new { @class = "norm-tb-text", @style = "width:300px" } })</td>
            <td>@Html.ValidationMessageFor(p => p.CurrAreaDesc)</td>

        </tr>        
        <tr>
            <!--string DisplayName = test.GetDisplayName(t => t.Name);-->
            <td>@Html.LabelFor(p=> p.CurrAreaLevel, new { htmlAttributes = new { @class = "norm-lab-level"} })</td>
            <td>@Html.EditorFor(p => p.CurrAreaLevel, new { htmlAttributes = new { @class = "norm-tb-text", @style = "width:50px" } })</td>
            <td>@Html.ValidationMessageFor(p => p.CurrAreaLevel)</td>
        </tr>        
        <tr>
            <td>@Html.LabelFor(p => p.CurrObs, new { htmlAttributes = new { @class = "norm-lab-text", @style = "width:300px" } })</td>
            <td>@Html.EditorFor(p => p.CurrObs, new { htmlAttributes = new { @class = "norm-tb-text", @style = "width:300px" } })</td>
            <td>@Html.ValidationMessageFor(p => p.CurrObs)</td>
        </tr>        
    </table>
    </div>
}

Views/TPerson/_LayPer.cshtml
@using MyErp.Models
@using System.Linq;
@using Microsoft.AspNetCore.Mvc.Localization

@using MyErp.Resources
@inject LocService SharedLocalizer
@*@model TPerson*@
@{
    Layout=null;
    Layout="~/Views/Shared/_Layout.cshtml";
}
@functions {
    @*
    string isGrid()
    {
        string ret="Nada";
        try{
            ret = ViewData["IdGrid"].ToString();
        }
        catch{}
        return ret;
    }
    string isFilter()
    {
        string ret="";
        try{
            ret = ViewData["Filter"].ToString();
        }
        catch{}
        return ret;

    }

    string isSort()
    {
        string ret="";
        try{
            ret = ViewData["Sort"].ToString();
        }
        catch{}
        return ret;

    }
    *@
    string panelBold(int panel)
    {      
        int tpan=0;  
        try{    
        tpan = (int)ViewData["panel"];
        }
        catch{}
        string cstyle ="";
        if (panel==tpan)
        {cstyle="font-weight:bold";}
        return cstyle;
    }
    string panelSel(int panel)
    {      
        int tpan=0;  
        try{    
        tpan = (int)ViewData["panel"];
        }
        catch{}
        string csel ="false";
        if (panel==tpan)
        {csel="true";}
        return csel;
    }
    string navClass(int panel)
    {
        int tpan=0;
        try{
            tpan=(int)ViewData["panel"];
        }
        catch{}
        string navcl="nav-link";
        if (panel==tpan)
        {navcl="nav-link active"; }
        return navcl;
        
    }
    string isVisible(int panel){
        string retcol="";
        int opanel =0;
        try{
        opanel = (int)ViewData["panel"];
        }
        catch{}
        if (opanel==panel){retcol="visible";}
        else{retcol="invisible";}
        return retcol;
    }
    int thisPanel(){
        int opanel =0;
        try{
         opanel = (int)ViewData["panel"];
        }
        catch{}
         return opanel;
    }
    int ModelPerId()
    {
        int pid =0;
        try{
        pid= (int)ViewData["PerId"];//0;//@Model.PerId;
        }
        catch{}
        return pid;
    }

    string dName()
    {
        string dname= (string)ViewData["dName"];//0;//@Model.PerId;
        return dname;
    }

}
@section Styles
{

}
<div class=" clearfix position-relative o_form_sheet center">

<h3 class ="style-h3">@SharedLocalizer.GetLocalizedHtmlString("EditPerson")</h3>
@using (Html.BeginForm()) {
    <table>
        <div>  @*class="cont-titles-l"*@
            <h4 class = "style-h4">@dName()</h4>
    	    <ul class="nav nav-tab">
	    	    <li class="nav-item">
                    <a class="nav-link"  role="tab" disable_anchor="true" asp-area="" asp-controller="TPerson" asp-action="Edit" asp-route-id="@ModelPerId()" asp-route-perid="@ModelPerId()" asp-route-panel="@thisPanel()" asp-route-move="1">@SharedLocalizer.GetLocalizedHtmlString("<<Prev")</a>
		        </li>
		        <li class="nav-item">
                    <a class="nav-link"  role="tab" disable_anchor="true" asp-area="" asp-controller="TPerson" asp-action="Edit" asp-route-id="@ModelPerId()" asp-route-perid="@ModelPerId()" asp-route-panel="@thisPanel()" asp-route-move="2" >@SharedLocalizer.GetLocalizedHtmlString("Next>>")</a>
		        </li>
		        <li class="nav-item">
                    <a class="nav-link"  role="tab" disable_anchor="true" asp-area="" asp-controller="TPerson" asp-action="" asp-route-id="@ModelPerId()" asp-route-perid="@ModelPerId()" asp-route-panel="@thisPanel()" asp-route-move="0" >@SharedLocalizer.GetLocalizedHtmlString("Home")</a>
		        </li>
            </ul>
        </div>
        @*asp-route-sortExpression="@isSort()" asp-route-filterExpression="@isFilter()"  asp-route-idgrid ="@isGrid()"*@
        <div>
	        <ul class="nav nav-tab">
		        <li class="nav-item">
                    <a class="@navClass(1)" role="tab" disable_anchor="true"  asp-area="" asp-controller="TPerson" asp-action="Edit" asp-route-id="@ModelPerId()" asp-route-perid="@ModelPerId()" asp-route-panel="1" asp-route-move="0" >@SharedLocalizer.GetLocalizedHtmlString("Person")</a>
		        </li>
		        <li class="nav-item">
                    <a class="@navClass(2)"  role="tab" disable_anchor="true"  asp-area="" asp-controller="TPerson" asp-action="Edit" asp-route-id="@ModelPerId()" asp-route-perid="@ModelPerId()" asp-route-panel="2" asp-route-move="0" >@SharedLocalizer.GetLocalizedHtmlString("Career")</a>
		        </li>
		        <li class="nav-item">
                    <a class="@navClass(3)"  role="tab" disable_anchor="true"  asp-area="" asp-controller="TPerson" asp-action="Edit" asp-route-id="@ModelPerId()" asp-route-perid="@ModelPerId()" asp-route-panel="3" asp-route-move="0" >@SharedLocalizer.GetLocalizedHtmlString("Contract")</a>
		        </li>
		        <li class="nav-item">
                    <a class="@navClass(4)"  role="tab" disable_anchor="true"  asp-area="" asp-controller="TPerson" asp-action="Edit" asp-route-id="@ModelPerId()" asp-route-perid="@ModelPerId()" asp-route-panel="4" asp-route-move="0" >@SharedLocalizer.GetLocalizedHtmlString("Curriculum")</a>
		        </li>
		        <li class="nav-item">
                    <a class="@navClass(5)"  role="tab" disable_anchor="true"  asp-area="" asp-controller="TPerson" asp-action="Edit" asp-route-id="@ModelPerId()" asp-route-perid="@ModelPerId()" asp-route-panel="5" asp-route-move="0" >@SharedLocalizer.GetLocalizedHtmlString("Pay")</a>
		        </li>
		        <li class="nav-item">
                    <a class="@navClass(6)"  role="tab" disable_anchor="true"  asp-area="" asp-controller="TPerson" asp-action="Edit" asp-route-id="@ModelPerId()" asp-route-perid="@ModelPerId()" asp-route-panel="6" asp-route-move="0" >@SharedLocalizer.GetLocalizedHtmlString("Presence")</a>
		        </li>
		        <li class="nav-item">
                    <a class="@navClass(7)"  role="tab" disable_anchor="true"  asp-area="" asp-controller="TPerson" asp-action="Edit" asp-route-id="@ModelPerId()" asp-route-perid="@ModelPerId()" asp-route-panel="7" asp-route-move="0" >@SharedLocalizer.GetLocalizedHtmlString("ObjReview")</a>
		        </li>
		        <li class="nav-item">
                    <a class="@navClass(8)"  role="tab" disable_anchor="true"  asp-area="" asp-controller="TPerson" asp-action="Edit" asp-route-id="@ModelPerId()" asp-route-perid="@ModelPerId()" asp-route-panel="8" asp-route-move="0" >@SharedLocalizer.GetLocalizedHtmlString("Training")</a>
		        </li>
	        </ul>
        </div>
    </table>
    @RenderBody()
}
</div>