Models/TSuplier.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace MyErp.Models
{
    public partial class TSuplier
    {
        public int SupId { get; set; }

        [Display(Name="SupRaSoc")]
        [Required,StringLength(125)]
        public string SupRasoc { get; set; }

        [Display(Name="NIF")]
        [Required,StringLength(10)]
        public string SupNif { get; set; }

        [Display(Name="SupCrDate")]
        [Required,DataType(DataType.Date)]         
        public DateTime? SupCrDate { get; set; }

        [Display(Name="SupCode")]
        [Required,StringLength(225)]
        public string SupCode { get; set; }

        [Display(Name="SupAccount")]
        [StringLength(225)]
        public string SupAcct { get; set; }

        [Display(Name="SupAdress")]
        [Required,StringLength(225)]
        public string SupAdStrt { get; set; }

        [Display(Name="SupAdressA")]
        [StringLength(225)]
        public string SupAdAdit { get; set; }

        [Display(Name="SupCity")]
        [Required,StringLength(225)]
        public string SupAdCity { get; set; }

        [Display(Name="SupCountry")]
        [Required,StringLength(4)]
        public string SupAdCtry { get; set; }

        [Display(Name="SupPhone")]
        [Required,StringLength(55)]
        public string SupCtPhone { get; set; }

        [Display(Name="SupemailLOG")]
        [Required,StringLength(125)]
        public string SupCtEmailLog { get; set; }

        [Display(Name="SupemailFIN")]
        [StringLength(125)]
        public string SupCtEmailFin { get; set; }

        [Display(Name="SupWebSite")]
        [StringLength(225)]
        public string SupCtWeb { get; set; }

        [Display(Name="SupEDILOG")]
        [Required,StringLength(100)]
        public string SupCtEdilog { get; set; }

        [Display(Name="SupEDIFIN")]
        [StringLength(100)]
        public string SupCtEdifin { get; set; }

        [Display(Name="SupBankAcc")]
        [StringLength(225)]
        public string SupCtBankAcc { get; set; }

        [Display(Name="SupStatus")]
        [StringLength(25)]
        public string SupStatus { get; set; }

        [Display(Name="SupStatusDate")]
        [DataType(DataType.Date)]         
        public DateTime? SupStDate { get; set; }
    }
}

Controllers/TSuplierController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyErp.Models;
using System.Linq;


using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MyErp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.SqlServer;
using Microsoft.Data.SqlClient;
using Microsoft.AspNetCore.Authorization;
using Microsoft.IdentityModel.Protocols;
using Microsoft.Extensions.Configuration;
using System.Data;
using System.Web;

namespace MyErp.Controllers {
    [Authorize(Roles="Supplier,Administrator")]
    public class TSuplierController : Controller {
        private readonly MyErpDBContext _dbContext;
        public TSuplierController(MyErpDBContext dbContext) {
            _dbContext = dbContext;
        }
        private void CreateViewBags(int? id, int? prod)
        {
            var queryca = from p in _dbContext.TSProducts 
                        orderby p.ProdRefer
                        where p.ProdSupId==id
                        select p;
            var qListca = queryca.ToList();
            ViewBag.ListProd=qListca;
            var queryco = from plan in _dbContext.TSPlannings
                        join pro in _dbContext.TSProducts on plan.PlanProdId equals pro.ProdId
                        join por in _dbContext.TSPorders 
                        on new {X1=plan.PlanSupId,X2=plan.PlanProdId} equals new {X1=por.SposupId,X2=por.SporeferEx}
                        join mat in _dbContext.TMaterials on por.SpocprodId equals mat.MatId
                        orderby plan.PlanProdId,plan.PlanDateFrom
                        where plan.PlanSupId==id //&& (plan.PlanProdId==prod ||prod==null || prod==0)
                        select new TSPlanningV {PlanSupId=plan.PlanSupId,PlanQty=plan.PlanQty,
                        PlanProdId=plan.PlanProdId,PlanId=plan.PlanId,PlanFirmSt=plan.PlanFirmSt,
                        PlanDateTo=plan.PlanDateTo,PlanDateFrom=plan.PlanDateFrom,
                        ProdSupId=pro.ProdSupId,ProdStDate=pro.ProdStDate,
                        ProdStatus=pro.ProdStatus,ProdId=pro.ProdId,ProdRefer=pro.ProdRefer,
                        ProdDescr=pro.ProdDescr,ProdCrDate=pro.ProdCrDate,
                        MatRefer=mat.MatRefer,MatDescr=mat.MatDescr};
            var qListco = queryco.ToList();
            ViewBag.ListPlan=qListco;

            /*2022-06-03 muestra descripcion interna y pasa codigo externo para el planning*/
            var result = from p in _dbContext.TSPorders
                        join  mat in _dbContext.TMaterials on p.SpocprodId equals mat.MatId
                        orderby mat.MatDescr
                        where p.SposupId==id
                        select new {p.SporeferEx,mat.MatDescr};
            ViewBag.ddlReferVB = new SelectList(result.ToList(), "SporeferEx", "MatDescr",prod); 
            
            var resuld = from  mat in _dbContext.TMaterials
                        orderby mat.MatDescr
                        where mat.MatClass=="RM"
                        select new {mat.MatId ,mat.MatDescr};
            ViewBag.ddlReferVD = new SelectList(resuld.ToList(), "MatId", "MatDescr",prod); 

            var querycx = from p in _dbContext.TSProducts 
                        orderby p.ProdDescr
                        where p.ProdSupId==id
                        select p;
            ViewBag.ddlReferEX = new SelectList(querycx.ToList(), "ProdId", "ProdDescr",prod); 

            var queryc = from p in _dbContext.TSupliers 
                        where p.SupId==id
                        select p;
            var qList=queryc.ToList();
            ViewBag.Suplier=qList[0];

           try{
            var mode = _dbContext.TSProducts
                .SingleOrDefault(u => u.ProdId.Equals(prod));
            ViewData["Prod"]=mode.ProdRefer;
            ViewData["cProd"]=prod;}
            catch{ViewData["Prod"]="No Filter <<<";
            ViewData["cProd"]=0;}

            /*
            var querypo_0 =(from po in _dbContext.TSPorders
                            join mat in _dbContext.TMaterials on po.SpocprodId equals mat.MatId 
                        orderby po.Spopo
                        where po.SposupId==id 
                        select new VTSPorder {Spoid=po.Spoid,SposupId=po.SposupId,Spopo=po.Spopo,SporeferEx=po.SporeferEx,
                                    SprodRefInt=mat.MatRefer,SpodescEx=po.SpodescEx,SprodDescInt=mat.MatDescr,
                                    Spoprice=po.Spoprice,Spocurcy=po.Spocurcy}).ToList();
            var querypo_1=(from po in _dbContext.TSPorders 
                        where  po.SposupId==id && (po.SpocprodId==null ||po.SpocprodId ==0) 
                        select new VTSPorder {Spoid=po.Spoid,SposupId=po.SposupId,Spopo=po.Spopo,SporeferEx=po.SporeferEx,
                                    SprodRefInt="NE",SpodescEx=po.SpodescEx,SprodDescInt="NE",
                                    Spoprice=po.Spoprice,Spocurcy=po.Spocurcy}).ToList();
            var querypo = querypo_0.Concat(querypo_1);
            var qListpo = querypo.ToList();

--------
            var qListpo =(from mat in _dbContext.TMaterials 
                            join po in _dbContext.TSPorders on mat.MatId equals  po.SpocprodId
                            join spr in _dbContext.TSProducts on po.SporeferEx equals spr.ProdId
---------

            */
            var qListpo =(from po in _dbContext.TSPorders
                            join mat in _dbContext.TMaterials on po.SpocprodId equals mat.MatId 
                            join spr in _dbContext.TSProducts on po.SporeferEx equals spr.ProdId
                        orderby po.Spopo
                        where po.SposupId==id 
                        select new VTSPorder {Spoid=po.Spoid,SposupId=po.SposupId,Spopo=po.Spopo,SporeferEx=spr.ProdRefer,
                                    SprodRefInt=mat.MatRefer,SpodescEx=spr.ProdDescr,SprodDescInt=mat.MatDescr,
                                    Spoprice=po.Spoprice,Spocurcy=po.Spocurcy,Spostatus=po.Spostatus,
                                    SpoPcRep=po.SpoPcRep,SpoDateSt=po.SpoDateSt}).ToList();
            ViewBag.ListSpo=qListpo;

        }

        public IActionResult Index(int filter,string pNam, string pNam1,string actionType) {
            if (actionType=="Cancel"){filter=0;}
            ViewData["Title"] = "All Items";
            ViewData["Filter"]=filter;
            ViewData["Fil1"]=pNam;
            ViewData["Fil2"]=pNam1;
            var dbContext = new MyErpDBContext();
            try{
             var model = _dbContext.TSupliers.OrderBy(p => p.SupRasoc).ToList();
             if (filter ==2){
                var queryc = from p in _dbContext.TSupliers 
                        where (p.SupRasoc.Contains(pNam) || pNam ==null ) && (p.SupNif.Contains(pNam1) ||pNam1==null)
                        orderby p.SupRasoc, p.SupNif
                        select p;
                var qList=queryc.ToList();
                model = qList;
             }
             return View(model);
            }
            catch{return View("Error");}
            
        }

        [HttpGet]
        public IActionResult Create() {
            ViewData["panel"]=1;

            return View();      
        }

        [HttpPost]
        public IActionResult Create(TSuplier suplier, string actionType) {
            ViewData["panel"]=1;
            if(actionType=="Add"){
            if (ModelState.IsValid){
            try{
                _dbContext.TSupliers.Add(suplier); 
                _dbContext.SaveChanges();
                }
            catch{}
            }
            else{
                 return View(suplier);
            }
            }
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult ProCreate(int Pid) {
            var queryc = from p in _dbContext.TSupliers 
                        where p.SupId==Pid
                        select p;
            var qList=queryc.ToList();
            ViewBag.Suplier=qList[0];

             var model = _dbContext.TSupliers
                .SingleOrDefault(u => u.SupId.Equals(Pid));

            string sName = model.SupRasoc+" " +model.SupNif;
            ViewData["sName"]=sName;
            ViewData["SupId"]=Pid;

            ViewData["panel"]=2;

            return View();      
        }

        [HttpPost]
        public IActionResult ProCreate(TSProduct product,int Pid, string actionType) {
            var model = _dbContext.TSupliers
                .SingleOrDefault(u => u.SupId.Equals(Pid));

            string sName = model.SupRasoc+" " +model.SupNif;
            ViewData["sName"]=sName;
            ViewData["SupId"]=Pid;

            if(actionType=="Add"){
            if (ModelState.IsValid){
            try{
                _dbContext.TSProducts.Add(product); 
                _dbContext.SaveChanges();
            }
            catch{return View("Error");}
            }
            else{
                CreateViewBags(Pid,product.ProdId);
                 return View(product);
            }
            }
            CreateViewBags(Pid,0);    
            ViewData["panel"]=2;
            return RedirectToAction("Edit",new{id=Pid,panel=2,move=0,prod=product.ProdId});

        }

        [HttpGet]
        public IActionResult PlanCreate(int Pid, int prod, string actionType) {
            var queryc = from p in _dbContext.TSupliers 
                        where p.SupId==Pid
                        select p;
            var qList=queryc.ToList();
            ViewBag.Suplier=qList[0];

             var model = _dbContext.TSupliers
                .SingleOrDefault(u => u.SupId.Equals(Pid));

            string sName = model.SupRasoc+" " +model.SupNif;
            ViewData["sName"]=sName;
            ViewData["SupId"]=Pid;

Views/TSuplier/PoCreate.cshtml
@using MyErp.Models
@model TSPorder
@using MyErp.Resources
@inject LocService SharedLocalizer
@functions {
    int? Planta(){
        int? retcol = (int?)ViewData["Plant"];
        return retcol;
    }
}
@{
    Layout = "_LaySup";
}
<div class="style-data">
<h3>@SharedLocalizer.GetLocalizedHtmlString("AddPORecord")</h3>
</div>
@using (Html.BeginForm()) {
    <div class="div-edit">
    @Html.ValidationSummary(true)
    <div class ="invisible">
        <tr>
            <input type="hidden" name="SposupId" value="@(((TSuplier)ViewBag.Suplier).SupId)"/>
            <td>@SharedLocalizer.GetLocalizedHtmlString("Suplier"):</td>
            <td>@(((TSuplier)ViewBag.Suplier).SupRasoc)</td>
        </tr>
    </div>
    <table class="table-edit">
        <hr style="width:100%;text-align:left;margin-left:0">        
        <tr>
            <td><input type="submit" class="dropbtn" value="Add"  name="actionType"/></td>
            <td><input type="submit" class="dropbtn" value="Cancel" name="actionType"/></td>
        </tr>
        @Html.Partial("_pshowspo",Model)
    </table>
    </div>
}

Views/TSuplier/_LaySup copy.cshtml
@using MyErp.Models
@using System.Linq;
@using Microsoft.AspNetCore.Mvc.Localization

@using MyErp.Resources
@inject LocService SharedLocalizer
@*@model TPerson*@
@{
    Layout=null;
    Layout="~/Views/Shared/_Layout.cshtml";
}

@*
@functions {
    @_
    string isGrid()
    {
        string ret="Nada";
        try{
            ret = ViewData["IdGrid"].ToString();
        }
        catch{}
        return ret;
    }
    string isFilter()
    {
        string ret="";
        try{
            ret = ViewData["Filter"].ToString();
        }
        catch{}
        return ret;

    }

    string isSort()
    {
        string ret="";
        try{
            ret = ViewData["Sort"].ToString();
        }
        catch{}
        return ret;

    }
    _@
    string panelBold(int panel)
    {      
        int tpan=0;  
        try{    
        tpan = (int)ViewData["panel"];
        }
        catch{}
        string cstyle ="";
        if (panel==tpan)
        {cstyle="font-weight:bold";}
        return cstyle;
    }
    string panelSel(int panel)
    {      
        int tpan=0;  
        try{    
        tpan = (int)ViewData["panel"];
        }
        catch{}
        string csel ="false";
        if (panel==tpan)
        {csel="true";}
        return csel;
    }
    string navClass(int panel)
    {
        int tpan=0;
        try{
            tpan=(int)ViewData["panel"];
        }
        catch{}
        string navcl="nav-link";
        if (panel==tpan)
        {navcl="nav-link active"; }
        return navcl;
        
    }
    string isVisible(int panel){
        string retcol="";
        int opanel =0;
        try{
        opanel = (int)ViewData["panel"];
        }
        catch{}
        if (opanel==panel){retcol="visible";}
        else{retcol="invisible";}
        return retcol;
    }
    int thisPanel(){
        int opanel =0;
        try{
         opanel = (int)ViewData["panel"];
        }
        catch{}
         return opanel;
    }
    int ModelPerId()
    {
        int pid =0;
        try{
        pid= (int)ViewData["PerId"];//0;//@Model.PerId;
        }
        catch{}
        return pid;
    }

    string dName()
    {
        string dname= (string)ViewData["dName"];//0;//@Model.PerId;
        return dname;
    }

}
*@
@functions {
    string navClass(int panel)
    {
        int tpan=0;
        try{
            tpan=(int)ViewData["panel"];
        }
        catch{}
        string navcl="nav-link";
        if (panel==tpan)
        {navcl="nav-link active"; }
        return navcl;
        
    }
    string panelBold(int panel)
    {            
        int tpan = 1;
        try{
            tpan=(int)ViewData["panel"];
        }
        catch{}
        string cstyle ="";
        if (panel==tpan)
        {cstyle="font-weight:bold";}
        return cstyle;
    }

    string isVisible(int panel){
        string retcol="";
        int opanel = (int)ViewData["panel"];
        if (opanel==panel){retcol="visible";}
        else{retcol="invisible";}
        return retcol;
    }
    int thisPanel(){
         int opanel =1;
         try{
            opanel=  (int)ViewData["panel"];
         }
         catch{}
         return opanel;
    }
    int ModelSupId()
    {
        int pid =0;
        try{
        pid= (int)ViewData["SupId"];//0;//@Model.PerId;
        }
        catch{}
        return pid;
    }

    string sName()
    {
        string dname= (string)ViewData["sName"];//0;//@Model.PerId;
        return dname;
    }

}

@section Styles
{

}

<h3 class ="style-h3">@SharedLocalizer.GetLocalizedHtmlString("EditSuplier")</h3>
@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <table>
        <div>  @*class="cont-titles-l"*@
            <h4 class = "style-h4">@sName()</h4>
    	    <ul class="nav nav-tab">
	    	    <li class="nav-item">
                    <a class="nav-link"  role="tab" disable_anchor="true" style="@panelBold(0)" asp-area="" asp-controller="TSuplier" asp-action="Edit" asp-route-id="@ModelSupId()" asp-route-perid="@ModelSupId()" asp-route-panel="@thisPanel()" asp-route-move="1">@SharedLocalizer.GetLocalizedHtmlString("<<Prev")</a>
		        </li>
		        <li class="nav-item">
                    <a class="nav-link"  role="tab" style="@panelBold(0)" disable_anchor="true" asp-area="" asp-controller="TSuplier" asp-action="Edit" asp-route-id="@ModelSupId()" asp-route-perid="@ModelSupId()" asp-route-panel="@thisPanel()" asp-route-move="2" >@SharedLocalizer.GetLocalizedHtmlString("Next>>")</a>
		        </li>
		        <li class="nav-item">
                    <a class="nav-link"  role="tab" disable_anchor="true" asp-area="" asp-controller="TSuplier" asp-action="" asp-route-id="@ModelSupId()" asp-route-perid="@ModelSupId()" asp-route-panel="@thisPanel()" asp-route-move="2" >@SharedLocalizer.GetLocalizedHtmlString("Home")</a>
		        </li>
            </ul>
        </div>
        @*asp-route-sortExpression="@isSort()" asp-route-filterExpression="@isFilter()"  asp-route-idgrid ="@isGrid()"*@
        <div>
	        <ul class="nav nav-tab">
		        <li class="nav-item">
                    <a class="@navClass(1)" role="tab" disable_anchor="true" style="@panelBold(1)" asp-area="" asp-controller="TSuplier" asp-action="Edit" asp-route-id="@ModelSupId()" asp-route-perid="@ModelSupId()" asp-route-panel="1" asp-route-move="0" >@SharedLocalizer.GetLocalizedHtmlString("Suplier")</a>
		        </li>
		        <li class="nav-item">
                    <a class="@navClass(2)"  role="tab" disable_anchor="true" style="@panelBold(2)" asp-area="" asp-controller="TSuplier" asp-action="Edit" asp-route-id="@ModelSupId()" asp-route-perid="@ModelSupId()" asp-route-panel="2" asp-route-move="0" >@SharedLocalizer.GetLocalizedHtmlString("Products")</a>
		        </li>
		        <li class="nav-item">
                    <a class="@navClass(4)"  role="tab" disable_anchor="true" style="@panelBold(4)" asp-area="" asp-controller="TSuplier" asp-action="Edit" asp-route-id="@ModelSupId()" asp-route-perid="@ModelSupId()" asp-route-panel="4" asp-route-move="0" >@SharedLocalizer.GetLocalizedHtmlString("Orders")</a>
		        </li>
		        <li class="nav-item">
                    <a class="@navClass(3)"  role="tab" disable_anchor="true" style="@panelBold(3)" asp-area="" asp-controller="TSuplier" asp-action="Edit" asp-route-id="@ModelSupId()" asp-route-perid="@ModelSupId()" asp-route-panel="3" asp-route-move="0" >@SharedLocalizer.GetLocalizedHtmlString("Planning")</a>
		        </li>
		        <li class="nav-item">
                    <a class="@navClass(5)"  role="tab" disable_anchor="true" style="@panelBold(0)" asp-area="" asp-controller="TSuplier" asp-action="Index" >@SharedLocalizer.GetLocalizedHtmlString("Suppliers")</a>
		        </li>
	        </ul>
        </div>
    </table>
    @RenderBody()
}

Views/TSuplier/_LaySup.cshtml
@using MyErp.Models
@using System.Linq;
@using Microsoft.AspNetCore.Mvc.Localization

@using MyErp.Resources
@inject LocService SharedLocalizer
@*@model TPerson*@
@{
    Layout=null;
    Layout="~/Views/Shared/_Layout.cshtml";
}

@*
@functions {
    @_
    string isGrid()
    {
        string ret="Nada";
        try{
            ret = ViewData["IdGrid"].ToString();
        }
        catch{}
        return ret;
    }
    string isFilter()
    {
        string ret="";
        try{
            ret = ViewData["Filter"].ToString();
        }
        catch{}
        return ret;

    }

    string isSort()
    {
        string ret="";
        try{
            ret = ViewData["Sort"].ToString();
        }
        catch{}
        return ret;

    }
    _@
    string panelBold(int panel)
    {      
        int tpan=0;  
        try{    
        tpan = (int)ViewData["panel"];
        }
        catch{}
        string cstyle ="";
        if (panel==tpan)
        {cstyle="font-weight:bold";}
        return cstyle;
    }
    string panelSel(int panel)
    {      
        int tpan=0;  
        try{    
        tpan = (int)ViewData["panel"];
        }
        catch{}
        string csel ="false";
        if (panel==tpan)
        {csel="true";}
        return csel;
    }
    string navClass(int panel)
    {
        int tpan=0;
        try{
            tpan=(int)ViewData["panel"];
        }
        catch{}
        string navcl="nav-link";
        if (panel==tpan)
        {navcl="nav-link active"; }
        return navcl;
        
    }
    string isVisible(int panel){
        string retcol="";
        int opanel =0;
        try{
        opanel = (int)ViewData["panel"];
        }
        catch{}
        if (opanel==panel){retcol="visible";}
        else{retcol="invisible";}
        return retcol;
    }
    int thisPanel(){
        int opanel =0;
        try{
         opanel = (int)ViewData["panel"];
        }
        catch{}
         return opanel;
    }
    int ModelPerId()
    {
        int pid =0;
        try{
        pid= (int)ViewData["PerId"];//0;//@Model.PerId;
        }
        catch{}
        return pid;
    }

    string dName()
    {
        string dname= (string)ViewData["dName"];//0;//@Model.PerId;
        return dname;
    }

}
*@
@functions {
    string navClass(int panel)
    {
        int tpan=0;
        try{
            tpan=(int)ViewData["panel"];
        }
        catch{}
        string navcl="nav-link";
        if (panel==tpan)
        {navcl="nav-link active"; }
        return navcl;
        
    }
    string panelBold(int panel)
    {            
        int tpan = 1;
        try{
            tpan=(int)ViewData["panel"];
        }
        catch{}
        string cstyle ="";
        if (panel==tpan)
        {cstyle="font-weight:bold";}
        return cstyle;
    }

    string isVisible(int panel){
        string retcol="";
        int opanel = (int)ViewData["panel"];
        if (opanel==panel){retcol="visible";}
        else{retcol="invisible";}
        return retcol;
    }
    int thisPanel(){
         int opanel =1;
         try{
            opanel=  (int)ViewData["panel"];
         }
         catch{}
         return opanel;
    }
    int ModelSupId()
    {
        int pid =0;
        try{
        pid= (int)ViewData["SupId"];//0;//@Model.PerId;
        }
        catch{}
        return pid;
    }

    string sName()
    {
        string dname= (string)ViewData["sName"];//0;//@Model.PerId;
        return dname;
    }

}

@section Styles
{

}
<div class=" clearfix position-relative o_form_sheet center">

<h3 class ="style-h3">@SharedLocalizer.GetLocalizedHtmlString("EditSuplier")</h3>
@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <table>
        <div>  @*class="cont-titles-l"*@
            <h4 class = "style-h4">@sName()</h4>
    	    <ul class="nav nav-tab">
	    	    <li class="nav-item">
                    <a class="nav-link"  role="tab" disable_anchor="true" style="@panelBold(0)" asp-area="" asp-controller="TSuplier" asp-action="Edit" asp-route-id="@ModelSupId()" asp-route-perid="@ModelSupId()" asp-route-panel="@thisPanel()" asp-route-move="1">@SharedLocalizer.GetLocalizedHtmlString("<<Prev")</a>
		        </li>
		        <li class="nav-item">
                    <a class="nav-link"  role="tab" style="@panelBold(0)" disable_anchor="true" asp-area="" asp-controller="TSuplier" asp-action="Edit" asp-route-id="@ModelSupId()" asp-route-perid="@ModelSupId()" asp-route-panel="@thisPanel()" asp-route-move="2" >@SharedLocalizer.GetLocalizedHtmlString("Next>>")</a>
		        </li>
		        <li class="nav-item">
                    <a class="nav-link"  role="tab" disable_anchor="true" asp-area="" asp-controller="TSuplier" asp-action="" asp-route-id="@ModelSupId()" asp-route-perid="@ModelSupId()" asp-route-panel="@thisPanel()" asp-route-move="0" >@SharedLocalizer.GetLocalizedHtmlString("Home")</a>
		        </li>
            </ul>
        </div>
        @*asp-route-sortExpression="@isSort()" asp-route-filterExpression="@isFilter()"  asp-route-idgrid ="@isGrid()"*@
        <div>
	        <ul class="nav nav-tab">
		        <li class="nav-item">
                    <a class="@navClass(1)" role="tab" disable_anchor="true" style="@panelBold(1)" asp-area="" asp-controller="TSuplier" asp-action="Edit" asp-route-id="@ModelSupId()" asp-route-perid="@ModelSupId()" asp-route-panel="1" asp-route-move="0" >@SharedLocalizer.GetLocalizedHtmlString("Suplier")</a>
		        </li>
		        <li class="nav-item">
                    <a class="@navClass(2)"  role="tab" disable_anchor="true" style="@panelBold(2)" asp-area="" asp-controller="TSuplier" asp-action="Edit" asp-route-id="@ModelSupId()" asp-route-perid="@ModelSupId()" asp-route-panel="2" asp-route-move="0" >@SharedLocalizer.GetLocalizedHtmlString("Products")</a>
		        </li>
		        <li class="nav-item">
                    <a class="@navClass(4)"  role="tab" disable_anchor="true" style="@panelBold(4)" asp-area="" asp-controller="TSuplier" asp-action="Edit" asp-route-id="@ModelSupId()" asp-route-perid="@ModelSupId()" asp-route-panel="4" asp-route-move="0" >@SharedLocalizer.GetLocalizedHtmlString("Orders")</a>
		        </li>
		        <li class="nav-item">
                    <a class="@navClass(3)"  role="tab" disable_anchor="true" style="@panelBold(3)" asp-area="" asp-controller="TSuplier" asp-action="Edit" asp-route-id="@ModelSupId()" asp-route-perid="@ModelSupId()" asp-route-panel="3" asp-route-move="0" >@SharedLocalizer.GetLocalizedHtmlString("Planning")</a>
		        </li>
                @*
		        <li class="nav-item">
                    <a class="@navClass(5)"  role="tab" disable_anchor="true" style="@panelBold(0)" asp-area="" asp-controller="TSuplier" asp-action="Index" >@SharedLocalizer.GetLocalizedHtmlString("Suppliers")</a>
		        </li>
                *@
	        </ul>
        </div>
    </table>
    @RenderBody()
}
</div>

Views/TSuplier/_xViewStart.cshtml
@{
    Layout = "_Layout";
}